// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0T2W0ElfQXrRhAANgMHBucgLSeESoPnY',
    appId: '1:605294250474:web:c73a10104fbda2275dca93',
    messagingSenderId: '605294250474',
    projectId: 'studio-4308693113-a4650',
    authDomain: 'studio-4308693113-a4650.firebaseapp.com',
    storageBucket: 'studio-4308693113-a4650.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2gu4oxeLU6wxR_BA3uELkmkwFiQr2jE',
    appId: '1:605294250474:android:9cf767491ed868965dca93',
    messagingSenderId: '605294250474',
    projectId: 'studio-4308693113-a4650',
    storageBucket: 'studio-4308693113-a4650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL89IKHGcKg3f-bN9dAGdKE4H59HViNnI',
    appId: '1:605294250474:ios:b128ef96c798b5305dca93',
    messagingSenderId: '605294250474',
    projectId: 'studio-4308693113-a4650',
    storageBucket: 'studio-4308693113-a4650.firebasestorage.app',
    iosClientId: '605294250474-c7jqonqejp3dp1oev8fe7eihsg1oq1tr.apps.googleusercontent.com',
    iosBundleId: 'com.plads20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL89IKHGcKg3f-bN9dAGdKE4H59HViNnI',
    appId: '1:605294250474:ios:1ffba7ca9fa694fe5dca93',
    messagingSenderId: '605294250474',
    projectId: 'studio-4308693113-a4650',
    storageBucket: 'studio-4308693113-a4650.firebasestorage.app',
    iosClientId: '605294250474-cmn20krud2hngji5l50tgig18avp6jte.apps.googleusercontent.com',
    iosBundleId: 'com.example.plads20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0T2W0ElfQXrRhAANgMHBucgLSeESoPnY',
    appId: '1:605294250474:web:3c6cdd4f1584a5da5dca93',
    messagingSenderId: '605294250474',
    projectId: 'studio-4308693113-a4650',
    authDomain: 'studio-4308693113-a4650.firebaseapp.com',
    storageBucket: 'studio-4308693113-a4650.firebasestorage.app',
  );
}
