import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart'; // Import kIsWeb
import 'package:firebase_core/firebase_core.dart';
import 'package:intl/date_symbol_data_local.dart'; // Import for locale data
import 'screens/splash_screen.dart';
import 'package:provider/provider.dart';
import 'services/auth_service.dart';
import 'services/firestore_service.dart';
import 'services/notification_service.dart';
import 'services/academy_service.dart';
import 'services/storage_service.dart';
import 'services/subscription_service.dart';
import 'models/user_model.dart';
import 'screens/login_screen.dart';
import 'screens/instructor/instructor_home_screen.dart';
import 'screens/student/student_main_screen.dart';

import 'package:shared_preferences/shared_preferences.dart';

import 'firebase_options.dart'; // Generated by flutterfire configure

// Global Theme Notifier for easy access
final ValueNotifier<ThemeMode> themeNotifier = ValueNotifier(ThemeMode.system);

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeDateFormatting('es_CL', null); // Initialize Spanish (Chile) locale
  
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    
    // Load saved theme
    final prefs = await SharedPreferences.getInstance();
    final String? themeString = prefs.getString('themeMode');
    if (themeString != null) {
      if (themeString == 'ThemeMode.dark') themeNotifier.value = ThemeMode.dark;
      else if (themeString == 'ThemeMode.light') themeNotifier.value = ThemeMode.light;
      else themeNotifier.value = ThemeMode.system;
    }

    runApp(const MyApp());
  } catch (e) {
    runApp(MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.black,
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Text(
              'Error fatal al iniciar:\n$e',
              style: const TextStyle(color: Colors.red, fontSize: 16),
              textAlign: TextAlign.center,
            ),
          ),
        ),
      ),
    ));
  }
}



class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<AuthService>(create: (_) => AuthService()),
        Provider<FirestoreService>(create: (_) => FirestoreService()),
        Provider<NotificationService>(create: (_) => NotificationService()),
        Provider<StorageService>(create: (_) => StorageService()),
        Provider<SubscriptionService>(create: (_) => SubscriptionService()),
        ChangeNotifierProvider<AcademyService>(create: (_) => AcademyService()),
      ],
      child: ValueListenableBuilder<ThemeMode>(
        valueListenable: themeNotifier,
        builder: (context, currentMode, child) {
          return MaterialApp(
            title: 'Plads App',
            debugShowCheckedModeBanner: false,
            themeMode: currentMode,
            theme: ThemeData(
              brightness: Brightness.light,
              scaffoldBackgroundColor: Colors.grey.shade100,
              appBarTheme: const AppBarTheme(
                backgroundColor: Colors.white,
                iconTheme: IconThemeData(color: Colors.black),
                titleTextStyle: TextStyle(color: Colors.black, fontSize: 20, fontWeight: FontWeight.bold),
                elevation: 0,
              ),
              colorScheme: ColorScheme.fromSeed(
                seedColor: const Color(0xFF39FF14),
                brightness: Brightness.light,
              ),
              useMaterial3: true,
            ),
            darkTheme: ThemeData(
              brightness: Brightness.dark,
              scaffoldBackgroundColor: Colors.black,
              appBarTheme: const AppBarTheme(
                backgroundColor: Colors.black,
                iconTheme: IconThemeData(color: Colors.white),
                titleTextStyle: TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold),
                elevation: 0,
              ),
              colorScheme: ColorScheme.fromSeed(
                seedColor: const Color(0xFF39FF14),
                brightness: Brightness.dark,
                surface: Colors.black,
              ),
            useMaterial3: true,
            ),
            home: const AuthWrapper(),
          );
        },
      ),
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthService>(context);
    
    return StreamBuilder<UserModel?>(
      stream: authService.user,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.active) {
          final UserModel? user = snapshot.data;
          if (user == null) {
            return const LoginScreen();
          }
          if (user.role == 'instructor') {
            return const InstructorHomeScreen();
          } else {
            return const StudentMainScreen();
          }
        }
        return const SplashScreen();
      },
    );
  }
}
